options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1800s"  # 30 minutos
substitutions:
  _REGION: "us-east1"
  _PROJECT_ID: "attetioncore-dev"       # reemplaza con tu project id
  _REPO_NAME: "springboot-repo"
  _IMAGE_NAME: "pruebagcp-app"
  _GKE_CLUSTER: "autopilot-cluster-1"

steps:
  # Build Gradle (usa JDK 25)
  - name: 'gradle:9.0-jdk25'
    entrypoint: 'bash'
    args:
      - '-c'
      - './gradlew clean build --no-daemon'
    id: 'Gradle Build'

  # Build Docker image (multi-stage con Java 25 y Gradle)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'deployment/Dockerfile',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}',
      '.'
    ]
    id: 'Build Docker Image'

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
    ]
    id: 'Push Docker Image'

  # Get GKE credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_GKE_CLUSTER} \
          --region ${_REGION} \
          --project ${_PROJECT_ID}

  # Deploy to GKE in namespace pruebas
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|IMAGE_PLACEHOLDER|${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}|g" k8s/deployment.yaml
        
        kubectl apply -f k8s/deployment.yaml -n pruebas
        kubectl apply -f k8s/service.yaml -n pruebas
        kubectl apply -f k8s/hpa.yaml -n pruebas
        
        kubectl rollout status deployment/${_IMAGE_NAME} -n pruebas --timeout=120s

  # Tag latest if branch is master
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          docker tag ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA} \
            ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest
          docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest
        fi
